# =============================================================================
# Cluster Definition: Development (Demo)
# =============================================================================
apiVersion: fleet.cattle.io/v1alpha1
kind: Cluster
metadata:
  name: dawet-dev
  namespace: fleet-default
  labels:
    env: dev
    region: id-jkt
spec:
  kubeConfigSecret: dawet-dev-kubeconfig
