# =============================================================================
# Namespaces - Fleet Bundle (Demo)
# =============================================================================
defaultNamespace: cattle-fleet-system

targetCustomizations:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev

labels:
  bundle: namespaces
