#  =============================================================================
# Redis - Fleet Bundle (Demo)
#  =============================================================================
# Step 4: Required by Dify, Milvus, n8n
#  =============================================================================

defaultNamespace: redis-system

helm:
 repo: https://charts.bitnami.com/bitnami/
 chart: redis
 version: 25.3.9
 releaseName: redis
 valuesFiles:
   - values.yaml

 
targetCustomizations:
 - name: dev
   clusterSelector:
     matchLabels:
       env: dev

labels:
 bundle: redis
