# =============================================================================
# Redis - Fleet Bundle (Demo)
# =============================================================================
# Required: Dify, Milvus, n8n
# =============================================================================

defaultNamespace: redis-system

helm:
  repo: https://charts.bitnami.com/bitnami/
  chart: redis
  version: 19.6.0
  releaseName: redis
  valuesFiles:
    - values.yaml

dependsOn:
  - selector:
      matchLabels:
        bundle: namespaces

targetCustomizations:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev

labels:
  bundle: redis
