# =============================================================================
# Local Path Provisioner - Fleet Bundle (Demo)
# =============================================================================

defaultNamespace: local-path-storage

helm:
  repo: https://charts.containeroo.ch
  chart: local-path-provisioner
  version: 0.0.28
  releaseName: local-path-provisioner
  valuesFiles:
    - values.yaml

targetCustomizations:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev

labels:
  bundle: local-path-provisioner
