#  =============================================================================
# PostgreSQL Cluster - Fleet Bundle (Demo)
#  =============================================================================
# Step 3: PostgreSQL instance for grafana_db
#  =============================================================================

defaultNamespace: postgres-system

helm:
 repo: https://charts.bitnami.com/bitnami/
 chart: postgresql
 version: 18.5.14
 releaseName: postgres-grafana
 valuesFiles:
   - values-grafana.yaml

 
targetCustomizations:
 - name: dev
   clusterSelector:
     matchLabels:
       env: dev

labels:
 bundle: postgres-cluster
